# IMPORTANT: any modification requires to also be written inside the package.yaml

version: '3'
services:
  rsyslog:
    image: iox-syslog-relay
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "514:514/udp"
    volumes:
      - work:/var/lib/rsyslog
    restart: always
volumes:
  work: