descriptor-schema-version: "2.7"
info:
  name: iox-syslog-relay
  description: Reliable syslog relay for IOx
  version: latest
  author-name: Egon Scheer <e.scheer@student.uliege.be>
app:
  cpuarch: arm64
  env:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    TZ: UTC
  resources:
    cpu: "400"
    memory: "128"
    network:
    - interface-name: eth0
      ports:
        udp:
        - 514
    profile: custom
  startup:
    rootfs: rootfs.tar
    target:
    - ./start.sh
  type: docker
