version: '3'
services:
  rsyslog:
    image: iox-syslog-relay
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "514:514/udp"
    volumes:
      - work:/var/lib/rsyslog
    environment:
      - ELASTIC_HOST=host.docker.internal
      - ELASTIC_PORT=9200
      - REMOTE_HOST=host.docker.internal
      - REMOTE_PORT=10514
      - ELASTIC_UID=elastic
      - ELASTIC_PWD=elastic
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
volumes:
  work: