version: '3'
services:
  rsyslog:
    image: escheer/syslog-relay
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "514:514/udp"
    volumes:
      - ./work:/var/lib/rsyslog
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    